### PR TITLE
 Bugfix: SLM should not use ssm specific broker to communicate with placement executive plugin.

### PR DESCRIPTION
**Pull request by tsoenen**

### CODE REVIEW

**Comment by tsoenen** [comment]
Test this please

**Comment by tsoenen** [comment]
Test this please

**Comment by tsoenen** [comment]
Test this please

**Comment by tsoenen** [comment]
Test this please

**Comment by tsoenen** [comment]
Test this please

**Comment by tsoenen** [comment]
test this please

**Comment by tsoenen** [comment]
test this please

**Comment by tsoenen** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
Test this please

**Pull request merged**
