### PR TITLE
SSM/FSM support, termination workflow support, virtual host support from SLM and FLM.

### PR DESCRIPTION
**Pull request by tsoenen**

### CODE REVIEW

**Comment by tsoenen** [comment]
test this please

**Comment by tsoenen** [comment]
test this please

**Comment by tsoenen** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by tsoenen** [comment]
test this please

**Pull request merged**
