### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by tsoenen**

### CODE REVIEW

**Comment by tsoenen** [comment]
test this please

**Comment by tsoenen** [comment]
@mpeuster @hadik3r @felipevicens Someone an idea why the Jenkins job keeps failing? Seems to be related to the broker, but I can't figure out what. Someone had this issue before?

**Comment by mpeuster** [comment]
No died. I checked the AMQPStorm PyPi page (https://pypi.python.org/pypi/AMQPStorm) because I thought that there was maybe a change, but it does not seem to be the issue. What else could have changed from the running version to this version?

**Comment by tsoenen** [comment]
After successfully running the job from Jenkins with the master branch, this PR passes the test. Some strange voodoo magic going on:p

**Pull request closed without merging**
